aws:
  name: AWS
  fields:
    - key: AWS_ACCESS_KEY_ID
      description: Your AWS access key ID.
    - key: AWS_SECRET_ACCESS_KEY
      description: Your AWS secret access key.
azure:
  name: Azure
  fields:
    - key: AZURE_TENANT_ID
      description: Your Azure tenant ID.
    - key: AZURE_CLIENT_ID
      description: Your Azure client ID.
    - key: AZURE_CLIENT_SECRET
      description: Your Azure client secret.
openai:
  name: OpenAI
  fields:
    - key: OPENAI_ORG_ID
      description: Your OpenAI org ID.
    - key: OPENAI_API_KEY
      description: Your OpenAI API key.
